### ISSUE TITLE
Is there any way to include wiki-style links

### ISSUE THREAD

**Issue by cglacet** [cglacet/bear#4]
> For me those are a lot handier, since I can simply create a new page without manually creating one and getting the link of it. I wouldn't mind the reference links to be in the bear-style in order to avoid the circle reference described in your implementation notes.

> Concerning wiki-style links: there are two ways to link notes in bear.
> 1. Link to notes, manually to be created via right click in the notes list -> copy link
> 2. 'Auto-complete' links [as they call them](https://bear.app/faq/Tags%20&%20Linking/How%20to%20link%20notes%20together/). Entering `[[` within a note will start searching for note titles and link the respective note. If there is no such note it will create a new one. 
>
> I only use the later ones in my workflow, since I barely have the notes list visible and find it a lot more intuitive to link the pages this way.

_Originally posted by @benjaminharr in https://github.com/cglacet/bear/issues/2#issuecomment-625986498_ and https://github.com/cglacet/bear/issues/2#issuecomment-626160349

**Comment by cglacet** [comment]
According to the format I think this shouldn't be a problem to implement for simple cases, but I'm not too sure how this work if, for example, two notes share the exact same title.

**Comment by cglacet** [comment]
I tried it and even bear can't deal with duplicate titles, so there is no real solution to this. On the other hand I can implement a solution that would work in other cases (I feel like duplicate title is the only hard case). 

If you have two notes with title `Note A` bear link will not be tight to either of those but instead to the most recently modified. I think I can reproduce this behaviour.

**Comment by cglacet** [comment]
I've updated the code in the [wikilinks](https://github.com/cglacet/bear/tree/wikilinks) branch so we try it out. 

Here is [what it would look like](https://github.com/cglacet/bear/tree/35f9d8e70ab69817a37d93176590cbc1802af213#wiki-links-style-references) (I added the strange behaviour we would have with two notes sharing the same title).

If you want to try it out, you need to switch to the test branch in your local copy of this repository:

```bash
# depending on where you installed it, this should be the default:
cd ~/.github/bear/back-references  
git fetch
git checkout -t remotes/origin/wikilinks
python insert_backreferences.py
```

**Comment by benjaminharr** [comment]
Awesome, works like a charm! 

Two things I'd love to improve (might be translated into separate issues/features)
1. remove the `/` at the end of a backlink if in main section. I'd expect the slash only to appear if the link comes from a sub-section.
2. Add option to auto-execute or schedule the script. I will temporarily set up an Alfredo workflow to execute via shortcut. Might include an auto-backup before executing as well.

**Comment by cglacet** [comment]
@benjaminharr 

Actually, 1. already works, you can use the environment variable `BEAR_ROOT_SECTION_TEXT` to define your own label (here an empty one) for the root section:

```bash
BEAR_ROOT_SECTION_TEXT='' \
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/cglacet/bear/master/install.sh)"
```

Or, since you probably work with the python script directly: 
```bash
BEAR_ROOT_SECTION_TEXT='' \
python insert_backreferences.py
```

Other available options are documented [here](https://github.com/cglacet/bear#complete-documentation-on-environment-variable-options). I should add an option to modify the "note - section" separator too. 

I also think 2. would be nice, not sure how to do it yet :). This would also help to solve other problems (like modification dates of notes).

**Comment by cglacet** [comment]
> ```shell
> # depending on where you installed it, this should be the default:
> cd ~/.github/bear/back-references  
> git fetch
> git checkout -t remotes/origin/wikilinks
> python insert_backreferences.py
> ```
